version: 2.1


orbs:
  heroku: circleci/heroku@0.0.6


commands:
  cargo:
    description: "Run cargo command with specific Rust version"
    parameters:
      command:
        type: string
      rust_channel:
        type: string
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Cargo << parameters.command >> all targets with Rust version << parameters.rust_channel >>
          command: cargo << parameters.command >> --all --all-targets --all-features --examples
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-<< parameters.rust_channel >>-{{ arch }}-{{ checksum "Cargo.lock" }}


aliases:
  - &image-1-34
    docker:
      - image: rust:1.34
  - &image-stable
    docker:
      - image: rust:latest
  - &image-nightly
    docker:
      - image: rustlang/rust:nightly
  - &jobs-check-build-test
    - check-1-34
    - build-1-34:
        requires:
          - check-1-34
    - test-1-34:
        requires:
          - build-1-34
    - check-stable
    - build-stable:
        requires:
          - check-stable
    - test-stable:
        requires:
          - build-stable

jobs:
  check-1-34:
    <<: *image-1-34
    steps:
      - cargo:
          command: check
          rust_channel: 1-34
  check-stable:
    <<: *image-stable
    steps:
      - cargo:
          command: check
          rust_channel: stable
  check-nightly:
    <<: *image-nightly
    steps:
      - cargo:
          command: check
          rust_channel: nightly
  build-1-34:
    <<: *image-1-34
    steps:
      - cargo:
          command: build
          rust_channel: 1-34
  build-stable:
    <<: *image-stable
    steps:
      - cargo:
          command: build
          rust_channel: stable
  build-nightly:
    <<: *image-nightly
    steps:
      - cargo:
          command: build
          rust_channel: nightly
  test-1-34:
    <<: *image-1-34
    steps:
      - cargo:
          command: test
          rust_channel: 1-34
  test-stable:
    <<: *image-stable
    steps:
      - cargo:
          command: test
          rust_channel: stable
  test-nightly:
    <<: *image-nightly
    steps:
      - cargo:
          command: test
          rust_channel: nightly


workflows:
  version: 2
  check-build-test:
    jobs:
      *jobs-check-build-test
  cron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      *jobs-check-build-test

